### ISSUE TITLE
图形验证码乱码

### ISSUE THREAD

**Issue by Moyce** [elunez/eladmin-doc#36]
![image](https://user-images.githubusercontent.com/20234273/85354179-8f982700-b53c-11ea-8659-d708d8faeca4.png)

**Comment by jaysng** [comment]
一毛一样

**Comment by jaysng** [comment]
已解决：
以下分享解决思路和步骤：
1、F12，发现code接口请求返回200正常
2、将本地环境的验证码对应的base64替换到生产环境的页面中，发现能正常显示，确定非前端部署问题，是后端接口问题
3、仔细对比两套环境的接口返回参数，发现base64编码出现大量重复连续的乱码，怀疑是base64编码有问题
4、对比两套环境区别，JDK版本均为1.8，本地环境MACOS，服务器为Ubuntu；同时比对本地和生产环境配置，发现properites文件中验证码属性code_type:chinese_gif，而开发环境是arithmetic；
至此，问题已解决，虽未从根本解决问题，但不影响正常使用。

**Comment by Moyce** [comment]
已解决，我是把redis库切换到其它库一切正常发自我的华为手机-------- 原始邮件 --------发件人： jaysng <notifications@github.com>日期： 2020年6月27日周六 00:55收件人： elunez/eladmin-doc <eladmin-doc@noreply.github.com>抄送： Moyce <msc947526548@163.com>, Author <author@noreply.github.com>主    题： Re: [elunez/eladmin-doc] 图形验证码乱码 (#36)
已解决：
以下分享解决思路和步骤：
1、F12，发现code接口请求返回200正常
2、将本地环境的验证码对应的base64替换到生产环境的页面中，发现能正常显示，确定非前端部署问题，是后端接口问题
3、仔细对比两套环境的接口返回参数，发现base64编码出现大量重复连续的乱码，怀疑是base64编码有问题
4、对比两套环境区别，JDK版本均为1.8，本地环境MACOS，服务器为Ubuntu；同时比对本地和生产环境配置，发现properites文件中验证码属性code_type:chinese_gif，而开发环境是arithmetic；
至此，问题已解决，虽未从根本解决问题，但不影响正常使用。
