### ISSUE TITLE
[Vssue]快速开始 | EL-ADMIN 在线文档

### ISSUE THREAD

**Issue by elunez** [elunez/eladmin-doc#60]
https://el-admin.vip/pages/010103/

**Comment by pstruggle** [comment]
vscode 怎么解决 mapstruct 的实现类不会自动生成 的问题呢

**Comment by elunez** [comment]
@pstruggle

> vscode 怎么解决 mapstruct 的实现类不会自动生成 的问题呢

没用过，尝试手动生成吧

**Comment by heroyang11** [comment]
qq群的文档域名是是啥啊，求

**Comment by elunez** [comment]
@heroyang11

> qq群的文档域名是是啥啊，求
> 

el-admin.vip

如果加不进去，可以换个平台的QQ试试。

**Comment by xuzhihao150429** [comment]
前端安装install 总失败，分别安装了 python和vs 都不行，直接删了

**Comment by suisuiyi** [comment]
后端应用里有个 ”45.properties“ ，发现工程里没有呢

    /**
     * 获取配置信息
     */
    public static PropertiesConfiguration getConfig() {
        try {
            return new PropertiesConfiguration("45.properties");
        } catch (Throwable e) {
            log.error(e.getMessage(), e);
        }
        return null;
    }

**Comment by xinxingi** [comment]
端口号已经变了，server:port: 8000
