### ISSUE TITLE
[Vssue]通用查询 | EL-ADMIN 在线文档

### ISSUE THREAD

**Issue by elunez** [elunez/eladmin-doc#63]
https://el-admin.vip/pages/010203/

**Comment by linshimingyi** [comment]
请问 怎么使用多表关联时的多字段模糊查询呢？
比如，select a.* from a left join b on a.id = b.a_id left join c on a.id = c._a_id where b.name = ? and c.status = ? 这样一个sql，应该怎么实现呢？感谢

**Comment by elunez** [comment]
@linshimingyi

> 请问 怎么使用多表关联时的多字段模糊查询呢？
> 比如，select a.* from a left join b on a.id = b.a_id left join c on a.id = c._a_id where b.name = ? and c.status = ? 这样一个sql，应该怎么实现呢？感谢

```java
@Query(joinName = "", propName="", join = Query.Join.RIGHT)
// 指定type为模糊查询就行 type = Query.Type.
```
