### ISSUE TITLE
[Vssue]常见问题 | EL-ADMIN 在线文档

### ISSUE THREAD

**Issue by elunez** [elunez/eladmin-doc#82]
https://el-admin.vip/pages/020101/

**Comment by huangfengjing** [comment]
前端有没有计划采用VUE3重写？

**Comment by elunez** [comment]
@huangfengjing

> 前端有没有计划采用VUE3重写？

暂无

**Comment by EricDaiJiaQi** [comment]
布到线上之后刷新页面时404是什么原因？

**Comment by elunez** [comment]
@EricDaiJiaQi

> 布到线上之后刷新页面时404是什么原因？

https://el-admin.vip/pages/010401/#%E5%89%8D%E7%AB%AF%E9%83%A8%E7%BD%B2

**Comment by hetingting2020** [comment]
可以增加拦截重复提交请求的功能吗？
